# Change these first
owner: sven0219 # Your GitHub organization or username, where this repository lives
repo: statusPages # The name of this repository

sites:
  - name: Blog
    url: https://www.svenshen.com
  - name: Apac-jp
    url: https://hiltonhotels.jp
  - name: Apac-kr
    url: http://hilton.co.kr
  - name: Bomsven
    url: http://www.bomsven.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.svenshen.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status Pages 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
